version: "2"
services:
  go-server:
    image: gocd/gocd-server:v18.6.0
    links:
      - svn-server
    ports:
      - '8153:8153'
      - '8154:8154'
    volumes:
      - ./test/godata/config:/godata/config

  go-agent:
    image: gocd/gocd-agent-alpine-3.6:v18.6.0
    links:
      - go-server
      - svn-server
    environment:
      AGENT_AUTO_REGISTER_KEY: '123456789abcdef'
      GO_SERVER_URL: https://go-server:8154/go

  svn-server:
    image: mamohr/subversion-edge
    ports:
      - '3343:3343'
      - '4434:4434'
      - '18080:18080'
    volumes:
      - ./test/svn-data:/opt/csvn/data
